spring:
  application:
    name: PostService
  data:
    mongodb:
      uri: mongodb+srv://deva:deva123@atlascluster.inazn0l.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
      database: TravelBuddy

server:
  port: 8080

travelbuddy:
  collection:
    posts: Posts
  deletedPostsCollection: DeletedPosts
  inactivePostsCollection: InactivePosts

eureka:
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: https://travelbuddy-servicediscovery-production.up.railway.app/eureka/